language: python

python:
  - "2.7"

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# comando para rodas os testes
script: 
  coverage run manage.py test

after_success:
  coveralls