language: python

python:
  - "2.7"

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# configurações do banco de dados teste
before_escript:
  #- psql -c "CREATE USER telefonia WITH PASSWORD 'telefonia';" -U postgres
  - psql -c "CREATE ROLE telefonia SUPERUSER PASSWORD 'telefonia';" -U postgres
  #- psql -c "ALTER ROLE telefonia WITH LOGIN ENCRYPTED PASSWORD 'telefonia';" -U postgres
  #- psql -c "ALTER USER telefonia CREATEDB;" -U postgres

# comando para rodas os testes
script: 
  coverage run manage.py test --settings=config.settings.test

after_success:
  coveralls