# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.DateField()),
                ('fechamento', models.DateField(blank=True, null=True)),
                ('solicitante', models.CharField(max_length=300)),
                ('problema', models.CharField(blank=True, max_length=500, null=True)),
                ('execucao', models.CharField(blank=True, max_length=300, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('executado', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'executores',
            },
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'problemas',
            },
        ),
        migrations.CreateModel(
            name='ProblemasComuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=500)),
                ('estimado', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.Departamento')),
            ],
            options={
                'verbose_name_plural': 'ramais',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrocaEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_velho', models.CharField(max_length=50, null=True)),
                ('serial_novo', models.CharField(max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.Chamado')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.TipoEquipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.Departamento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.Executor'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='problema_comum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.ProblemasComuns'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='ramal_atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramal_atendimento', to='telefonia.Ramal'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='ramal_contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramal_contato', to='telefonia.Ramal'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.Status'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='urgencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefonia.Urgencia'),
        ),
    ]
